#include "Arduino.h"
#include "assets.h"
#include "generated/c1_compressed.h"
#include "generated/c2_compressed.h"
#include "generated/c3_compressed.h"
#include "generated/c4_compressed.h"
#include "generated/splash_compressed.h"
